<?php

/**
 * @file
 * Install file for the Far Out Effects site. Based on Commerce Kickstart.
 */

/* --- HOOKS ---------------------------------------------------------------- */

/**
 * Implements hook_install().
 */
function farouteffects_install() {
  _farouteffects_add_default_text_format();
  _farouteffects_enable_blocks();
  _farouteffects_add_content_types();
  _farouteffects_add_menu_items();
  _farouteffects_add_shortcuts();
  _farouteffects_update_permissions();
  _farouteffects_update_variables();
}
