<?php
/**
 * @file
 * Provides an example payment method for Drupal Commerce for testing and
 *   development.
 */

/**
 * Implements hook_commerce_payment_method_info().
 */
function farout_payment_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods['farout_payment'] = array(
    'title' => t('Dummy payment'),
    'description' => t('A dummy payment method for farouteffects.dk.'),
    'active' => TRUE,
  );

  return $payment_methods;
}

/**
 * Payment method callback: submit form.
 */
function farout_payment_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $form = array();

  // Merge in values from the order.
  if (!empty($order->data['farout_payment'])) {
    $pane_values += $order->data['farout_payment'];
  }

  return $form;
}

/**
 * Payment method callback: submit form submission.
 */
function farout_payment_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  $order->data['farout_payment'] = $pane_values;

  farout_payment_transaction($payment_method, $order, $charge, $pane_values['name']);
}

/**
 * Creates a payment transaction for the specified charge amount.
 *
 * @param $payment_method
 *   The payment method instance object used to charge this payment.
 * @param $order
 *   The order object the payment applies to.
 * @param $charge
 *   An array indicating the amount and currency code to charge.
 * @param $name
 *   The name entered on the submission form.
 */
function farout_payment_transaction($payment_method, $order, $charge, $name) {
  $transaction = commerce_payment_transaction_new('farout_payment', $order->order_id);
  $transaction->instance_id = $payment_method['instance_id'];
  $transaction->amount = $charge['amount'];
  $transaction->currency_code = $charge['currency_code'];
  $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;

  commerce_payment_transaction_save($transaction);
}
