<?php
/**
 * @file
 * Custom functionality for the Far Out Effects site.
 */

/* --- HOOKS --------------------------------------------------------------- */

/**
 * Implements hook_views_api().
 */
function farout_site_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array('version' => 2);
  }
}

/**
 * Implements hook_node_view().
 */
function farout_site_node_view($node, $view_mode, $langcode) {
  if ('farout_product_display' == $node->type && 'teaser' != $view_mode) {
    if (!empty($node->field_farout_product_category['und'][0])) {
      $tid = $node->field_farout_product_category['und'][0]['tid'];

      $item = menu_get_item();
      $item['href'] = 'taxonomy/term/' . $tid;
      menu_set_item(NULL, $item);

      drupal_set_breadcrumb(_farout_site_get_breadcrumbs());
    }
  }
}

/**
 * Implements hook_image_default_styles().
 */
function farout_site_image_default_styles() {
  $styles = array();

  $styles['farout_featured'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array('width' => 220, 'height' => 220),
        'weight' => 0,
      ),
    )
  );

  $styles['farout_grid'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array('width' => 220, 'height' => 220),
        'weight' => 0,
      ),
    )
  );

  $styles['farout_large'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale',
        'data' => array('width' => 460, 'height' => 0, 'upscale' => 1),
        'weight' => 0,
      ),
    )
  );

  $styles['farout_thumbnail'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop',
        'data' => array('width' => 140, 'height' => 140),
        'weight' => 0,
      ),
    )
  );

  return $styles;
}

/* --- UTILITY -------------------------------------------------------------- */

function _farout_site_get_breadcrumbs() {
  $item = menu_get_item();
  $tree = menu_tree_page_data('main-menu');
  $crumbs = array(l(t('Home'), '<front>'));
  _farout_site_recurse_crumbs($tree, $item, $crumbs);
  return $crumbs;
}

function _farout_site_recurse_crumbs($tree, $item, &$crumbs, $above = array()) {
  foreach ($tree as $menu_item) {
    if (!$menu_item['link']['in_active_trail']) {
      continue;
    }
    if ($menu_item['link']['link_path'] == $item['href']) {
      foreach ($above as $trail_item) {
        $crumbs[] = l($trail_item['link']['link_title'], $trail_item['link']['link_path']);
      }
      $crumbs[] = l($menu_item['link']['link_title'], $menu_item['link']['link_path']);
      break;
    }
    if (is_array($menu_item['below'])) {
      _farout_site_recurse_crumbs($menu_item['below'], $item, $crumbs, array_merge($above, array($menu_item)));
    }
  }
}
